language: php
before_script: echo 'zend_extension=opcache.so' >> ~/.phpenv/versions/5.6/etc/conf.d/travis.ini
script: phpunit tests
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3
notifications:
  email: false
