language: php
before_script: echo 'extension=apc.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script: phpunit tests
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3
notifications:
  email: false
